# Generated by Django 5.0.3 on 2024-06-08 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseApp', '0002_rename_course_code_course_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='number_of_hours',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
